### ISSUE TITLE
not enough values to unpack crash observed 2x recently

### ISSUE THREAD

**Issue by ggggggggg** [usnistgov/dastardcommander#79]
This doesn't happen right away, but it has happened in a day or less two times so far on horton. I think I started `DASTARD` and `dastardcommander` then adjusted nothing, so no sources were active. 

Here is all the output from `dastardcommander`. 
```
Dastard is at localhost:5500
Collecting updates from dastard at tcp://localhost:5501
SEND SourceControl.SendAllStatus "dummy"
STATUS     0: {'Running': False, 'SourceName': 'Lancero', 'Nchannels': 128, 'Nsamples': 3000, 'Npresamp': 1500, 'SamplePeriod': 1920, 'Ncol': [8], 'Nrow': [8], 'ChannelsWithProjectors': []}
Error processing status message [topic,msg]: CURRENTTIME, 
Error is: Expecting value: line 1 column 1 (char 0)
LANCERO     1: {'FiberMask': 65535, 'CardDelay': [1], 'ActiveCards': [0], 'ShouldAutoRestart': False, 'DastardOutput': {'Nsamp': 4, 'ClockMHz': 125, 'AvailableCards': [], 'Lsync': 30, 'Settle': 24, 'SequenceLength': 8, 'PropagationDelay': 10, 'BAD16CardDelay': 0}}
ROACH     2: {'HostPort': [], 'Rates': []}
ABACO     3: {'ActiveCards': [], 'AvailableCards': []}
STATUS     4: {'Running': False, 'SourceName': 'Lancero', 'Nchannels': 128, 'Nsamples': 3000, 'Npresamp': 1500, 'SamplePeriod': 1920, 'Ncol': [8], 'Nrow': [8], 'ChannelsWithProjectors': []}
WRITING     5: {'Active': False, 'Paused': False, 'BasePath': '/media/pcuser/HHD2/horton', 'FilenamePattern': '', 'ExperimentStateFilename': '', 'ExperimentStateLabel': '', 'ExperimentStateLabelUnixNano': 0, 'ExternalTriggerFilename': '', 'DataDropFilename': ''}
{'Active': False, 'Paused': False, 'BasePath': '/media/pcuser/HHD2/horton', 'FilenamePattern': '', 'ExperimentStateFilename': '', 'ExperimentStateLabel': '', 'ExperimentStateLabelUnixNano': 0, 'ExternalTriggerFilename': '', 'DataDropFilename': ''}
STOPPED WRITING
ALIVE     6: {'Running': False, 'Time': 0, 'DataMB': 0}
SIMPULSE     7: {'Nchan': 1, 'SampleRate': 0, 'Pedestal': 0, 'Amplitudes': [], 'Nsamp': 0}
TRIANGLE     8: {'Nchan': 1, 'SampleRate': 0, 'Min': 0, 'Max': 0}
ALIVE     9: {'Running': False, 'Time': 0, 'DataMB': 0}
ALIVE    10: {'Running': False, 'Time': 0, 'DataMB': 0}
ALIVE    11: {'Running': False, 'Time': 0, 'DataMB': 0}
ALIVE    12: {'Running': False, 'Time': 0, 'DataMB': 0}
ALIVE    13: {'Running': False, 'Time': 0, 'DataMB': 0}
ALIVE    14: {'Running': False, 'Time': 0, 'DataMB': 0}
Traceback (most recent call last):
  File "/home/pcuser/qsp/src/dastardcommander/dastardcommander/status_monitor.py", line 41, in loop
    [topic, contents] = self.socket.recv_multipart()
ValueError: not enough values to unpack (expected 2, got 1)
```

Here is the last bit of output from `dastard`. This seems to have gone on for about one hour.
```
...
2020/04/02 09:07:42 new connection established
2020/04/02 09:07:44 new connection established
2020/04/02 09:07:47 new connection established
2020/04/02 09:07:52 new connection established
2020/04/02 09:07:57 new connection established
2020/04/02 09:08:02 new connection established
2020/04/02 09:08:12 new connection established
2020/04/02 09:10:19 new connection established
2020/04/02 09:13:55 new connection established
```

**Comment by ggggggggg** [comment]
This keeps happening, here is another seemingly identical event

```
Traceback (most recent call last):
  File "/home/pcuser/qsp/src/dastardcommander/dastardcommander/status_monitor.py", line 41, in loop
    [topic, contents] = self.socket.recv_multipart()
ValueError: not enough values to unpack (expected 2, got 1)
Aborted (core dumped)
```

**Comment by ggggggggg** [comment]
This crash is no longer happening, probably due to the change to `go-zeromq`. There are still new connections being established, but I've at least determined they are coming from somewhere else on this NIST network, so probably like IT security scanning us. Also now dastard spits out a bunch of ZMQ errors so I'm guessing that somehow replaced this `recv_multipart` error.
