### ISSUE TITLE
Bug in PR #82?

### ISSUE THREAD

**Issue by joefowler** [usnistgov/dastardcommander#85]
Crash when running latest dcom (after PR #82). I think this means that a setting, if never saved, defaults to an un-parseable value. I'll look into it...

```text
fowlerj@687figaro:dastardcommander$ dcom
Dastard is at localhost:5500
Traceback (most recent call last):
  File "/Users/fowlerj/Library/Python/3.8/bin/dcom", line 11, in <module>
    load_entry_point('dastardcommander', 'console_scripts', 'dcom')()
  File "/Users/fowlerj/Software/src/dastardcommander/dastardcommander/dc.py", line 990, in main
    dc = MainWindow(client, host, port)
  File "/Users/fowlerj/Software/src/dastardcommander/dastardcommander/dc.py", line 94, in __init__
    self.triggerTabSimple = trigger_config_simple.TriggerConfigSimple(self.tabTriggeringSimple, self)
  File "/Users/fowlerj/Software/src/dastardcommander/dastardcommander/trigger_config_simple.py", line 49, in __init__
    self.readSettings()
  File "/Users/fowlerj/Software/src/dastardcommander/dastardcommander/trigger_config_simple.py", line 156, in readSettings
    v = int(s.value("disable_zero_threshold")) # apparently QSettings sucks with bools, so use an int
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```

**Comment by ggggggggg** [comment]
https://github.com/usnistgov/dastardcommander/blob/9a1edee866bca7c0c681443f1d641367b8c7832b/dastardcommander/trigger_config_simple.py#L156

Yeah at line 156 it should have a default value of `0` or `False`.

**Comment by joefowler** [comment]
Got it. Haven't pushed yet, but I'm fixing it while I work on #83....
